version: '3'

services:
  oat-nginx:
    container_name: oat-nginx
    image: nginx:stable
    networks:
      - oat
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    working_dir: /etc/nginx/conf.d

  oat-phpfpm:
    container_name: oat-phpfpm
    env_file:
      - .env.docker
    build:
      context: ./docker/phpfpm
    environment:
      COMPOSER_AUTH: $COMPOSER_AUTH
    expose:
      - 9000
    networks:
      - oat
    volumes:
      - .:/var/www/html:cached
    working_dir: /var/www/html

networks:
  oat:
    driver: bridge